services:
  werkint_queue.repo.job:
    class:            Werkint\Bundle\QueueBundle\Entity\JobRepository
    factory_service:  doctrine.orm.entity_manager
    factory_method:   getRepository
    arguments: [WerkintQueueBundle:Job]
